// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

type Exploit struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Hash       string `json:"hash"`
	SubmitTime int64  `json:"submit_time"`
	Username   string `json:"username"`
	Version    int64  `json:"version"`
}

type Flag struct {
	ID           int64       `json:"id"`
	FlagCode     string      `json:"flag_code"`
	ServiceName  string      `json:"service_name"`
	PortService  uint16      `json:"port_service"`
	SubmitTime   uint64      `json:"submit_time"`
	ResponseTime uint64      `json:"response_time"`
	Msg          string      `json:"msg"`
	Status       int64       `json:"status"`
	TeamID       int64       `json:"team_id"`
	Username     string      `json:"username"`
	ExploitName  string      `json:"exploit_name"`
	DeletedAt    interface{} `json:"deleted_at"`
}
