// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Flag struct {
	FlagCode     string `json:"flag_code"`
	ServiceName  string `json:"service_name"`
	PortService  uint16 `json:"port_service"`
	SubmitTime   uint64 `json:"submit_time"`
	ResponseTime uint64 `json:"response_time"`
	Msg          string `json:"msg"`
	Status       string `json:"status"`
	TeamID       int64  `json:"team_id"`
	Username     string `json:"username"`
	ExploitName  string `json:"exploit_name"`
}
