// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const addFlag = `-- name: AddFlag :exec
INSERT OR IGNORE INTO flags(
	flag_code, service_name, port_service,
	submit_time, response_time, status,
	team_id, msg, username, exploit_name
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddFlagParams struct {
	FlagCode     string `json:"flag_code"`
	ServiceName  string `json:"service_name"`
	PortService  uint16 `json:"port_service"`
	SubmitTime   uint64 `json:"submit_time"`
	ResponseTime uint64 `json:"response_time"`
	Status       int64  `json:"status"`
	TeamID       int64  `json:"team_id"`
	Msg          string `json:"msg"`
	Username     string `json:"username"`
	ExploitName  string `json:"exploit_name"`
}

func (q *Queries) AddFlag(ctx context.Context, arg AddFlagParams) error {
	_, err := q.db.ExecContext(ctx, addFlag,
		arg.FlagCode,
		arg.ServiceName,
		arg.PortService,
		arg.SubmitTime,
		arg.ResponseTime,
		arg.Status,
		arg.TeamID,
		arg.Msg,
		arg.Username,
		arg.ExploitName,
	)
	return err
}

const countFilteredFlags = `-- name: CountFilteredFlags :one
SELECT COUNT(*) FROM flags
WHERE
    (team_id = ?1 OR ?1 IS NULL)
    AND (status = ?2 OR ?2 is NULL)
    AND (service_name = ?3 OR ?3 IS NULL)
    AND (
        ?4 IS NULL
        OR (
            (?5 = 'flag_code'    AND flag_code    LIKE ?6)
            OR (?5 = 'service_name' AND service_name LIKE ?6)
            OR (?5 = 'exploit_name' AND exploit_name LIKE ?6)
            OR (?5 = 'msg'          AND msg          LIKE ?6)
            OR (?5 = 'all' AND (
                flag_code    LIKE ?6
                OR service_name  LIKE ?6
                OR exploit_name  LIKE ?6
                OR msg           LIKE ?6
                OR CAST(team_id AS TEXT) LIKE ?6
            ))
            OR (?5 IS NULL AND flag_code LIKE ?6)
    )
)
`

type CountFilteredFlagsParams struct {
	TeamID      sql.NullInt64  `json:"team_id"`
	Status      sql.NullInt64  `json:"status"`
	ServiceName sql.NullString `json:"service_name"`
	Search      interface{}    `json:"search"`
	SearchField interface{}    `json:"search_field"`
	SearchLike  sql.NullString `json:"search_like"`
}

func (q *Queries) CountFilteredFlags(ctx context.Context, arg CountFilteredFlagsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFilteredFlags,
		arg.TeamID,
		arg.Status,
		arg.ServiceName,
		arg.Search,
		arg.SearchField,
		arg.SearchLike,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFlags = `-- name: CountFlags :one
SELECT COUNT(*)
FROM flags
LIMIT 1
`

func (q *Queries) CountFlags(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFlags)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExploit = `-- name: CreateExploit :exec

INSERT INTO exploits(name, hash, submit_time, username, version)
VALUES (?, ?, ?, ?, ?)
`

type CreateExploitParams struct {
	Name       string        `json:"name"`
	Hash       string        `json:"hash"`
	SubmitTime sql.NullInt64 `json:"submit_time"`
	Username   string        `json:"username"`
	Version    int64         `json:"version"`
}

func (q *Queries) CreateExploit(ctx context.Context, arg CreateExploitParams) error {
	_, err := q.db.ExecContext(ctx, createExploit,
		arg.Name,
		arg.Hash,
		arg.SubmitTime,
		arg.Username,
		arg.Version,
	)
	return err
}

const deleteFlagByCode = `-- name: DeleteFlagByCode :exec
DELETE FROM flags
WHERE flag_code = ?
`

func (q *Queries) DeleteFlagByCode(ctx context.Context, flagCode string) error {
	_, err := q.db.ExecContext(ctx, deleteFlagByCode, flagCode)
	return err
}

const deleteFlagByTTL = `-- name: DeleteFlagByTTL :execrows
DELETE FROM flags
WHERE response_time < (CAST(strftime('%s', 'now') AS INTEGER) - ?)
`

func (q *Queries) DeleteFlagByTTL(ctx context.Context, dollar_1 interface{}) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFlagByTTL, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const flagsStats = `-- name: FlagsStats :many
SELECT
    team_id,
    COUNT(*) AS total_flags,
    SUM(CASE WHEN status = 1 THEN 1 ELSE 0 END) AS accepted_flags,
    SUM(CASE WHEN status = 2 THEN 1 ELSE 0 END) AS denied_flags,
    SUM(CASE WHEN status = 0 THEN 1 ELSE 0 END) AS unsubmitted_flags,
    SUM(CASE WHEN status = 3 THEN 1 ELSE 0 END) AS error_flags,
    SUM(CASE WHEN status = 4 THEN 1 ELSE 0 END) AS not_valid_flags
FROM flags
GROUP BY team_id
ORDER BY team_id
`

type FlagsStatsRow struct {
	TeamID           int64           `json:"team_id"`
	TotalFlags       int64           `json:"total_flags"`
	AcceptedFlags    sql.NullFloat64 `json:"accepted_flags"`
	DeniedFlags      sql.NullFloat64 `json:"denied_flags"`
	UnsubmittedFlags sql.NullFloat64 `json:"unsubmitted_flags"`
	ErrorFlags       sql.NullFloat64 `json:"error_flags"`
	NotValidFlags    sql.NullFloat64 `json:"not_valid_flags"`
}

func (q *Queries) FlagsStats(ctx context.Context) ([]FlagsStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, flagsStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlagsStatsRow
	for rows.Next() {
		var i FlagsStatsRow
		if err := rows.Scan(
			&i.TeamID,
			&i.TotalFlags,
			&i.AcceptedFlags,
			&i.DeniedFlags,
			&i.UnsubmittedFlags,
			&i.ErrorFlags,
			&i.NotValidFlags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllExploits = `-- name: GetAllExploits :many
SELECT id, name, hash, submit_time, username, version
FROM exploits
ORDER BY submit_time DESC
`

func (q *Queries) GetAllExploits(ctx context.Context) ([]Exploit, error) {
	rows, err := q.db.QueryContext(ctx, getAllExploits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exploit
	for rows.Next() {
		var i Exploit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hash,
			&i.SubmitTime,
			&i.Username,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFlagCodes = `-- name: GetAllFlagCodes :many
SELECT flag_code FROM flags
`

func (q *Queries) GetAllFlagCodes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllFlagCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var flag_code string
		if err := rows.Scan(&flag_code); err != nil {
			return nil, err
		}
		items = append(items, flag_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFlags = `-- name: GetAllFlags :many
SELECT flag_code, service_name, port_service, submit_time, response_time, msg, status, team_id, username, exploit_name
FROM flags
ORDER BY submit_time DESC
`

func (q *Queries) GetAllFlags(ctx context.Context) ([]Flag, error) {
	rows, err := q.db.QueryContext(ctx, getAllFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flag
	for rows.Next() {
		var i Flag
		if err := rows.Scan(
			&i.FlagCode,
			&i.ServiceName,
			&i.PortService,
			&i.SubmitTime,
			&i.ResponseTime,
			&i.Msg,
			&i.Status,
			&i.TeamID,
			&i.Username,
			&i.ExploitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExploitByHash = `-- name: GetExploitByHash :one

SELECT id, name, hash, submit_time, username, version
FROM exploits
WHERE hash = ?
LIMIT 1
`

// EXPLOITS QUERIES
func (q *Queries) GetExploitByHash(ctx context.Context, hash string) (Exploit, error) {
	row := q.db.QueryRowContext(ctx, getExploitByHash, hash)
	var i Exploit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hash,
		&i.SubmitTime,
		&i.Username,
		&i.Version,
	)
	return i, err
}

const getExploitsByUsername = `-- name: GetExploitsByUsername :many
SELECT id, name, hash, submit_time, username, version
FROM exploits
WHERE username = ?
ORDER BY submit_time DESC
LIMIT ? OFFSET ?
`

type GetExploitsByUsernameParams struct {
	Username string `json:"username"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

func (q *Queries) GetExploitsByUsername(ctx context.Context, arg GetExploitsByUsernameParams) ([]Exploit, error) {
	rows, err := q.db.QueryContext(ctx, getExploitsByUsername, arg.Username, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exploit
	for rows.Next() {
		var i Exploit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hash,
			&i.SubmitTime,
			&i.Username,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilteredFlags = `-- name: GetFilteredFlags :many
SELECT flag_code, service_name, port_service, submit_time, response_time, msg, status, team_id, username, exploit_name FROM flags
WHERE
    (team_id = ?1 OR ?1 IS NULL)
    AND (status = ?2 OR ?2 IS NULL)
    AND (
        ?3 IS NULL
        OR (
            (?4 = 'flag_code'    AND flag_code    LIKE ?5)
            OR (?4 = 'service_name' AND service_name LIKE ?5)
            OR (?4 = 'exploit_name' AND exploit_name LIKE ?5)
            OR (?4 = 'msg'          AND msg          LIKE ?5)
            OR (?4 = 'all' AND (
                flag_code    LIKE ?5
                OR service_name  LIKE ?5
                OR exploit_name  LIKE ?5
                OR msg           LIKE ?5
                OR CAST(team_id AS TEXT) LIKE ?5
            ))
            OR (?4 IS NULL AND flag_code LIKE ?5)
        )
)
ORDER BY submit_time DESC
LIMIT ?7 OFFSET ?6
`

type GetFilteredFlagsParams struct {
	TeamID      sql.NullInt64  `json:"team_id"`
	Status      sql.NullInt64  `json:"status"`
	Search      interface{}    `json:"search"`
	SearchField interface{}    `json:"search_field"`
	SearchLike  sql.NullString `json:"search_like"`
	Offset      sql.NullInt64  `json:"offset"`
	Limit       sql.NullInt64  `json:"limit"`
}

func (q *Queries) GetFilteredFlags(ctx context.Context, arg GetFilteredFlagsParams) ([]Flag, error) {
	rows, err := q.db.QueryContext(ctx, getFilteredFlags,
		arg.TeamID,
		arg.Status,
		arg.Search,
		arg.SearchField,
		arg.SearchLike,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flag
	for rows.Next() {
		var i Flag
		if err := rows.Scan(
			&i.FlagCode,
			&i.ServiceName,
			&i.PortService,
			&i.SubmitTime,
			&i.ResponseTime,
			&i.Msg,
			&i.Status,
			&i.TeamID,
			&i.Username,
			&i.ExploitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFirstNFlagCodes = `-- name: GetFirstNFlagCodes :many
SELECT flag_code FROM flags
LIMIT ?
`

func (q *Queries) GetFirstNFlagCodes(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getFirstNFlagCodes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var flag_code string
		if err := rows.Scan(&flag_code); err != nil {
			return nil, err
		}
		items = append(items, flag_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFirstNFlags = `-- name: GetFirstNFlags :many
SELECT flag_code, service_name, port_service, submit_time, response_time, msg, status, team_id, username, exploit_name
FROM flags
ORDER BY submit_time DESC
LIMIT ?
`

func (q *Queries) GetFirstNFlags(ctx context.Context, limit int64) ([]Flag, error) {
	rows, err := q.db.QueryContext(ctx, getFirstNFlags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flag
	for rows.Next() {
		var i Flag
		if err := rows.Scan(
			&i.FlagCode,
			&i.ServiceName,
			&i.PortService,
			&i.SubmitTime,
			&i.ResponseTime,
			&i.Msg,
			&i.Status,
			&i.TeamID,
			&i.Username,
			&i.ExploitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlagByCode = `-- name: GetFlagByCode :one
SELECT flag_code, service_name, port_service, submit_time, response_time, msg, status, team_id, username, exploit_name
FROM flags
WHERE flag_code = ?
LIMIT 1
`

func (q *Queries) GetFlagByCode(ctx context.Context, flagCode string) (Flag, error) {
	row := q.db.QueryRowContext(ctx, getFlagByCode, flagCode)
	var i Flag
	err := row.Scan(
		&i.FlagCode,
		&i.ServiceName,
		&i.PortService,
		&i.SubmitTime,
		&i.ResponseTime,
		&i.Msg,
		&i.Status,
		&i.TeamID,
		&i.Username,
		&i.ExploitName,
	)
	return i, err
}

const getFlagsByTeam = `-- name: GetFlagsByTeam :many
SELECT flag_code, service_name, port_service, submit_time, response_time, msg, status, team_id, username, exploit_name
FROM flags
WHERE team_id = ?
ORDER BY submit_time DESC
LIMIT ? OFFSET ?
`

type GetFlagsByTeamParams struct {
	TeamID int64 `json:"team_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetFlagsByTeam(ctx context.Context, arg GetFlagsByTeamParams) ([]Flag, error) {
	rows, err := q.db.QueryContext(ctx, getFlagsByTeam, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flag
	for rows.Next() {
		var i Flag
		if err := rows.Scan(
			&i.FlagCode,
			&i.ServiceName,
			&i.PortService,
			&i.SubmitTime,
			&i.ResponseTime,
			&i.Msg,
			&i.Status,
			&i.TeamID,
			&i.Username,
			&i.ExploitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPagedFlagCodes = `-- name: GetPagedFlagCodes :many
SELECT flag_code FROM flags
LIMIT ? OFFSET ?
`

type GetPagedFlagCodesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetPagedFlagCodes(ctx context.Context, arg GetPagedFlagCodesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPagedFlagCodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var flag_code string
		if err := rows.Scan(&flag_code); err != nil {
			return nil, err
		}
		items = append(items, flag_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPagedFlags = `-- name: GetPagedFlags :many
SELECT flag_code, service_name, port_service, submit_time, response_time, msg, status, team_id, username, exploit_name
FROM flags
ORDER BY submit_time DESC
LIMIT ? OFFSET ?
`

type GetPagedFlagsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetPagedFlags(ctx context.Context, arg GetPagedFlagsParams) ([]Flag, error) {
	rows, err := q.db.QueryContext(ctx, getPagedFlags, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flag
	for rows.Next() {
		var i Flag
		if err := rows.Scan(
			&i.FlagCode,
			&i.ServiceName,
			&i.PortService,
			&i.SubmitTime,
			&i.ResponseTime,
			&i.Msg,
			&i.Status,
			&i.TeamID,
			&i.Username,
			&i.ExploitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnsubmittedFlagCodes = `-- name: GetUnsubmittedFlagCodes :many
SELECT flag_code FROM flags
WHERE status = 0
LIMIT ?
`

func (q *Queries) GetUnsubmittedFlagCodes(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUnsubmittedFlagCodes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var flag_code string
		if err := rows.Scan(&flag_code); err != nil {
			return nil, err
		}
		items = append(items, flag_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnsubmittedFlags = `-- name: GetUnsubmittedFlags :many
SELECT flag_code, service_name, port_service, submit_time, response_time, msg, status, team_id, username, exploit_name
FROM flags
WHERE status = 0
ORDER BY submit_time ASC
LIMIT ?
`

func (q *Queries) GetUnsubmittedFlags(ctx context.Context, limit int64) ([]Flag, error) {
	rows, err := q.db.QueryContext(ctx, getUnsubmittedFlags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flag
	for rows.Next() {
		var i Flag
		if err := rows.Scan(
			&i.FlagCode,
			&i.ServiceName,
			&i.PortService,
			&i.SubmitTime,
			&i.ResponseTime,
			&i.Msg,
			&i.Status,
			&i.TeamID,
			&i.Username,
			&i.ExploitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlagStatusByCode = `-- name: UpdateFlagStatusByCode :exec
UPDATE flags
SET
	status = ?,
	msg = ?,
	response_time = ?
WHERE flag_code = ?
`

type UpdateFlagStatusByCodeParams struct {
	Status       int64  `json:"status"`
	Msg          string `json:"msg"`
	ResponseTime uint64 `json:"response_time"`
	FlagCode     string `json:"flag_code"`
}

func (q *Queries) UpdateFlagStatusByCode(ctx context.Context, arg UpdateFlagStatusByCodeParams) error {
	_, err := q.db.ExecContext(ctx, updateFlagStatusByCode,
		arg.Status,
		arg.Msg,
		arg.ResponseTime,
		arg.FlagCode,
	)
	return err
}
