// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const addFlag = `-- name: AddFlag :exec
INSERT OR IGNORE INTO flags(
	flag_code, service_name, port_service,
	submit_time, response_time, status,
	team_id, msg, username, exploit_name
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddFlagParams struct {
	FlagCode     string `json:"flag_code"`
	ServiceName  string `json:"service_name"`
	PortService  uint16 `json:"port_service"`
	SubmitTime   uint64 `json:"submit_time"`
	ResponseTime uint64 `json:"response_time"`
	Status       int64  `json:"status"`
	TeamID       int64  `json:"team_id"`
	Msg          string `json:"msg"`
	Username     string `json:"username"`
	ExploitName  string `json:"exploit_name"`
}

func (q *Queries) AddFlag(ctx context.Context, arg AddFlagParams) error {
	_, err := q.db.ExecContext(ctx, addFlag,
		arg.FlagCode,
		arg.ServiceName,
		arg.PortService,
		arg.SubmitTime,
		arg.ResponseTime,
		arg.Status,
		arg.TeamID,
		arg.Msg,
		arg.Username,
		arg.ExploitName,
	)
	return err
}

const countExploits = `-- name: CountExploits :one
SELECT COUNT(*)
FROM exploits
LIMIT 1
`

func (q *Queries) CountExploits(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExploits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFilteredFlags = `-- name: CountFilteredFlags :one
SELECT COUNT(*) FROM flags
WHERE
    deleted_at IS NULL AND
    (team_id = ?1 OR ?1 IS NULL)
    AND (status = ?2 OR ?2 is NULL)
    AND (service_name = ?3 OR ?3 IS NULL)
    AND (
        ?4 IS NULL
        OR (
            (?5 = 'flag_code'    AND flag_code    LIKE ?4)
            OR (?5 = 'service_name' AND service_name LIKE ?4)
            OR (?5 = 'exploit_name' AND exploit_name LIKE ?4)
            OR (?5 = 'msg'          AND msg          LIKE ?4)
            OR (?5 = 'all' AND (
                flag_code    LIKE ?4
                OR service_name  LIKE ?4
                OR exploit_name  LIKE ?4
                OR msg           LIKE ?4
                OR CAST(team_id AS TEXT) LIKE ?4
            ))
            OR (?5 IS NULL AND flag_code LIKE ?4)
    )
)
`

type CountFilteredFlagsParams struct {
	TeamID      sql.NullInt64  `json:"team_id"`
	Status      sql.NullInt64  `json:"status"`
	ServiceName sql.NullString `json:"service_name"`
	Search      interface{}    `json:"search"`
	SearchField interface{}    `json:"search_field"`
}

func (q *Queries) CountFilteredFlags(ctx context.Context, arg CountFilteredFlagsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFilteredFlags,
		arg.TeamID,
		arg.Status,
		arg.ServiceName,
		arg.Search,
		arg.SearchField,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFlags = `-- name: CountFlags :one
SELECT COUNT(*)
FROM flags
WHERE deleted_at IS NULL
LIMIT 1
`

func (q *Queries) CountFlags(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFlags)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExploit = `-- name: CreateExploit :exec

INSERT INTO exploits(name, hash, submit_time, username, version)
VALUES (?, ?, ?, ?, ?)
`

type CreateExploitParams struct {
	Name       string `json:"name"`
	Hash       string `json:"hash"`
	SubmitTime int64  `json:"submit_time"`
	Username   string `json:"username"`
	Version    int64  `json:"version"`
}

func (q *Queries) CreateExploit(ctx context.Context, arg CreateExploitParams) error {
	_, err := q.db.ExecContext(ctx, createExploit,
		arg.Name,
		arg.Hash,
		arg.SubmitTime,
		arg.Username,
		arg.Version,
	)
	return err
}

const deleteExploitByID = `-- name: DeleteExploitByID :exec
DELETE FROM exploits
WHERE id = ?
`

func (q *Queries) DeleteExploitByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExploitByID, id)
	return err
}

const deleteFlagByCode = `-- name: DeleteFlagByCode :exec
UPDATE flags
SET deleted_at = CAST(strftime('%s', 'now') AS INTEGER)
WHERE flag_code = ?
AND deleted_at IS NULL
`

func (q *Queries) DeleteFlagByCode(ctx context.Context, flagCode string) error {
	_, err := q.db.ExecContext(ctx, deleteFlagByCode, flagCode)
	return err
}

const deleteFlagByTTL = `-- name: DeleteFlagByTTL :execrows
UPDATE flags
SET deleted_at = CAST(strftime('%s', 'now') AS INTEGER)
WHERE response_time < (CAST(strftime('%s', 'now') AS INTEGER) - ?)
AND deleted_at IS NULL
`

func (q *Queries) DeleteFlagByTTL(ctx context.Context, dollar_1 interface{}) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFlagByTTL, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const flagsExploitShare = `-- name: FlagsExploitShare :many
SELECT
	exploit_name,
	COUNT(*) AS value
FROM flags
WHERE exploit_name IS NOT NULL
GROUP BY exploit_name
ORDER BY value DESC, exploit_name
`

type FlagsExploitShareRow struct {
	ExploitName string `json:"exploit_name"`
	Value       int64  `json:"value"`
}

func (q *Queries) FlagsExploitShare(ctx context.Context) ([]FlagsExploitShareRow, error) {
	rows, err := q.db.QueryContext(ctx, flagsExploitShare)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlagsExploitShareRow
	for rows.Next() {
		var i FlagsExploitShareRow
		if err := rows.Scan(&i.ExploitName, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const flagsStats = `-- name: FlagsStats :many
SELECT
    team_id,
    COUNT(*) AS total_flags,
    SUM(status = 1) AS accepted_flags,
    SUM(status = 2) AS denied_flags,
    SUM(status = 0) AS unsubmitted_flags,
    SUM(status = 3) AS error_flags,
    SUM(status = 4) AS not_valid_flags
FROM flags
WHERE deleted_at IS NULL
GROUP BY team_id
ORDER BY team_id
`

type FlagsStatsRow struct {
	TeamID           int64           `json:"team_id"`
	TotalFlags       int64           `json:"total_flags"`
	AcceptedFlags    sql.NullFloat64 `json:"accepted_flags"`
	DeniedFlags      sql.NullFloat64 `json:"denied_flags"`
	UnsubmittedFlags sql.NullFloat64 `json:"unsubmitted_flags"`
	ErrorFlags       sql.NullFloat64 `json:"error_flags"`
	NotValidFlags    sql.NullFloat64 `json:"not_valid_flags"`
}

func (q *Queries) FlagsStats(ctx context.Context) ([]FlagsStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, flagsStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlagsStatsRow
	for rows.Next() {
		var i FlagsStatsRow
		if err := rows.Scan(
			&i.TeamID,
			&i.TotalFlags,
			&i.AcceptedFlags,
			&i.DeniedFlags,
			&i.UnsubmittedFlags,
			&i.ErrorFlags,
			&i.NotValidFlags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const flagsTickStats = `-- name: FlagsTickStats :many
SELECT
    submit_time / ? AS bucket,
    COUNT(*) AS total,
    SUM(status = 0) AS queued,
    SUM(status = 1) AS accepted,
    SUM(status = 2) AS denied,
    SUM(status = 3) AS error,
    SUM(status = 4) AS invalid
FROM flags
WHERE submit_time > 0
AND deleted_at IS NULL
GROUP BY bucket
ORDER BY bucket
`

type FlagsTickStatsRow struct {
	Bucket   int64           `json:"bucket"`
	Total    int64           `json:"total"`
	Queued   sql.NullFloat64 `json:"queued"`
	Accepted sql.NullFloat64 `json:"accepted"`
	Denied   sql.NullFloat64 `json:"denied"`
	Error    sql.NullFloat64 `json:"error"`
	Invalid  sql.NullFloat64 `json:"invalid"`
}

func (q *Queries) FlagsTickStats(ctx context.Context, submitTime uint64) ([]FlagsTickStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, flagsTickStats, submitTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlagsTickStatsRow
	for rows.Next() {
		var i FlagsTickStatsRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Total,
			&i.Queued,
			&i.Accepted,
			&i.Denied,
			&i.Error,
			&i.Invalid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllExploits = `-- name: GetAllExploits :many
SELECT id, name, hash, submit_time, username, version
FROM exploits
ORDER BY submit_time DESC
`

func (q *Queries) GetAllExploits(ctx context.Context) ([]Exploit, error) {
	rows, err := q.db.QueryContext(ctx, getAllExploits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exploit
	for rows.Next() {
		var i Exploit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hash,
			&i.SubmitTime,
			&i.Username,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFlagCodes = `-- name: GetAllFlagCodes :many
SELECT flag_code FROM flags WHERE deleted_at IS NULL
`

func (q *Queries) GetAllFlagCodes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllFlagCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var flag_code string
		if err := rows.Scan(&flag_code); err != nil {
			return nil, err
		}
		items = append(items, flag_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFlags = `-- name: GetAllFlags :many
SELECT id, flag_code, service_name, port_service, submit_time, response_time, msg, status, team_id, username, exploit_name, deleted_at
FROM flags
WHERE deleted_at IS NULL
ORDER BY submit_time DESC
`

func (q *Queries) GetAllFlags(ctx context.Context) ([]Flag, error) {
	rows, err := q.db.QueryContext(ctx, getAllFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flag
	for rows.Next() {
		var i Flag
		if err := rows.Scan(
			&i.ID,
			&i.FlagCode,
			&i.ServiceName,
			&i.PortService,
			&i.SubmitTime,
			&i.ResponseTime,
			&i.Msg,
			&i.Status,
			&i.TeamID,
			&i.Username,
			&i.ExploitName,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExploitByHash = `-- name: GetExploitByHash :one

SELECT id, name, hash, submit_time, username, version
FROM exploits
WHERE hash = ?
LIMIT 1
`

// EXPLOITS QUERIES
func (q *Queries) GetExploitByHash(ctx context.Context, hash string) (Exploit, error) {
	row := q.db.QueryRowContext(ctx, getExploitByHash, hash)
	var i Exploit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hash,
		&i.SubmitTime,
		&i.Username,
		&i.Version,
	)
	return i, err
}

const getExploitsByName = `-- name: GetExploitsByName :many
SELECT id, name, hash, submit_time, username, version
FROM exploits
WHERE name = ?
ORDER BY submit_time DESC
`

func (q *Queries) GetExploitsByName(ctx context.Context, name string) ([]Exploit, error) {
	rows, err := q.db.QueryContext(ctx, getExploitsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exploit
	for rows.Next() {
		var i Exploit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hash,
			&i.SubmitTime,
			&i.Username,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExploitsByUsername = `-- name: GetExploitsByUsername :many
SELECT id, name, hash, submit_time, username, version
FROM exploits
WHERE username = ? AND id > ?
ORDER BY submit_time DESC
LIMIT ?
`

type GetExploitsByUsernameParams struct {
	Username string `json:"username"`
	ID       int64  `json:"id"`
	Limit    int64  `json:"limit"`
}

func (q *Queries) GetExploitsByUsername(ctx context.Context, arg GetExploitsByUsernameParams) ([]Exploit, error) {
	rows, err := q.db.QueryContext(ctx, getExploitsByUsername, arg.Username, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exploit
	for rows.Next() {
		var i Exploit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hash,
			&i.SubmitTime,
			&i.Username,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilteredFlags = `-- name: GetFilteredFlags :many
WITH filtered AS (
    SELECT id, flag_code, service_name, port_service, submit_time, response_time, msg, status, team_id, username, exploit_name, deleted_at
    FROM flags
    WHERE
        deleted_at IS NULL
        AND (flags.team_id    = ?4      OR ?4      IS NULL)
        AND (flags.status     = ?5       OR ?5       IS NULL)
        AND (flags.service_name = ?6 OR ?6 IS NULL)
        AND (
            ?7 IS NULL
            OR (?8 = 'flag_code'    AND flags.flag_code    LIKE ?7)
            OR (?8 = 'service_name' AND flags.service_name LIKE ?7)
            OR (?8 = 'exploit_name' AND flags.exploit_name LIKE ?7)
            OR (?8 = 'msg'          AND flags.msg          LIKE ?7)
            OR (?8 = 'all' AND (
                flags.flag_code     LIKE ?7
                OR flags.service_name   LIKE ?7
                OR flags.exploit_name   LIKE ?7
                OR flags.msg            LIKE ?7
                OR CAST(flags.team_id AS TEXT) LIKE ?7
            ))
            OR (?8 IS NULL AND flags.flag_code LIKE ?7)
        )
)
SELECT id, flag_code, service_name, port_service, submit_time, response_time, msg, status, team_id, username, exploit_name, deleted_at FROM filtered
WHERE (
    ?1 IS NULL
    OR submit_time < ?1
    OR (submit_time = ?1 AND id < ?2)
)
ORDER BY submit_time DESC, id DESC
LIMIT ?3
`

type GetFilteredFlagsParams struct {
	CursorTime  interface{}    `json:"cursor_time"`
	CursorID    sql.NullInt64  `json:"cursor_id"`
	Limit       sql.NullInt64  `json:"limit"`
	TeamID      sql.NullInt64  `json:"team_id"`
	Status      sql.NullInt64  `json:"status"`
	ServiceName sql.NullString `json:"service_name"`
	Search      interface{}    `json:"search"`
	SearchField interface{}    `json:"search_field"`
}

type GetFilteredFlagsRow struct {
	ID           int64         `json:"id"`
	FlagCode     string        `json:"flag_code"`
	ServiceName  string        `json:"service_name"`
	PortService  int64         `json:"port_service"`
	SubmitTime   sql.NullInt64 `json:"submit_time"`
	ResponseTime sql.NullInt64 `json:"response_time"`
	Msg          string        `json:"msg"`
	Status       int64         `json:"status"`
	TeamID       int64         `json:"team_id"`
	Username     string        `json:"username"`
	ExploitName  string        `json:"exploit_name"`
	DeletedAt    interface{}   `json:"deleted_at"`
}

func (q *Queries) GetFilteredFlags(ctx context.Context, arg GetFilteredFlagsParams) ([]GetFilteredFlagsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFilteredFlags,
		arg.CursorTime,
		arg.CursorID,
		arg.Limit,
		arg.TeamID,
		arg.Status,
		arg.ServiceName,
		arg.Search,
		arg.SearchField,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilteredFlagsRow
	for rows.Next() {
		var i GetFilteredFlagsRow
		if err := rows.Scan(
			&i.ID,
			&i.FlagCode,
			&i.ServiceName,
			&i.PortService,
			&i.SubmitTime,
			&i.ResponseTime,
			&i.Msg,
			&i.Status,
			&i.TeamID,
			&i.Username,
			&i.ExploitName,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFirstNFlagCodes = `-- name: GetFirstNFlagCodes :many
SELECT flag_code FROM flags
WHERE deleted_at IS NULL
ORDER BY submit_time DESC
LIMIT ?
`

func (q *Queries) GetFirstNFlagCodes(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getFirstNFlagCodes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var flag_code string
		if err := rows.Scan(&flag_code); err != nil {
			return nil, err
		}
		items = append(items, flag_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFirstNFlags = `-- name: GetFirstNFlags :many
SELECT id, flag_code, service_name, port_service, submit_time, response_time, msg, status, team_id, username, exploit_name, deleted_at
FROM flags
WHERE deleted_at IS NULL
ORDER BY submit_time DESC
LIMIT ?
`

func (q *Queries) GetFirstNFlags(ctx context.Context, limit int64) ([]Flag, error) {
	rows, err := q.db.QueryContext(ctx, getFirstNFlags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flag
	for rows.Next() {
		var i Flag
		if err := rows.Scan(
			&i.ID,
			&i.FlagCode,
			&i.ServiceName,
			&i.PortService,
			&i.SubmitTime,
			&i.ResponseTime,
			&i.Msg,
			&i.Status,
			&i.TeamID,
			&i.Username,
			&i.ExploitName,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlagByCode = `-- name: GetFlagByCode :one
SELECT id, flag_code, service_name, port_service, submit_time, response_time, msg, status, team_id, username, exploit_name, deleted_at FROM flags
WHERE flag_code = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetFlagByCode(ctx context.Context, flagCode string) (Flag, error) {
	row := q.db.QueryRowContext(ctx, getFlagByCode, flagCode)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.FlagCode,
		&i.ServiceName,
		&i.PortService,
		&i.SubmitTime,
		&i.ResponseTime,
		&i.Msg,
		&i.Status,
		&i.TeamID,
		&i.Username,
		&i.ExploitName,
		&i.DeletedAt,
	)
	return i, err
}

const getUnsubmittedFlagCodes = `-- name: GetUnsubmittedFlagCodes :many
SELECT flag_code FROM flags
WHERE status = 0
AND deleted_at IS NULL
LIMIT ?
`

func (q *Queries) GetUnsubmittedFlagCodes(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUnsubmittedFlagCodes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var flag_code string
		if err := rows.Scan(&flag_code); err != nil {
			return nil, err
		}
		items = append(items, flag_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnsubmittedFlags = `-- name: GetUnsubmittedFlags :many
SELECT id, flag_code, service_name, port_service, submit_time, response_time, msg, status, team_id, username, exploit_name, deleted_at
FROM flags
WHERE status = 0
AND deleted_at IS NULL
ORDER BY submit_time ASC
LIMIT ?
`

func (q *Queries) GetUnsubmittedFlags(ctx context.Context, limit int64) ([]Flag, error) {
	rows, err := q.db.QueryContext(ctx, getUnsubmittedFlags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flag
	for rows.Next() {
		var i Flag
		if err := rows.Scan(
			&i.ID,
			&i.FlagCode,
			&i.ServiceName,
			&i.PortService,
			&i.SubmitTime,
			&i.ResponseTime,
			&i.Msg,
			&i.Status,
			&i.TeamID,
			&i.Username,
			&i.ExploitName,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlagStatusByCode = `-- name: UpdateFlagStatusByCode :exec
UPDATE flags
SET
	status = ?,
	msg = ?,
	response_time = ?
WHERE flag_code = ?
AND deleted_at IS NULL
`

type UpdateFlagStatusByCodeParams struct {
	Status       int64  `json:"status"`
	Msg          string `json:"msg"`
	ResponseTime uint64 `json:"response_time"`
	FlagCode     string `json:"flag_code"`
}

func (q *Queries) UpdateFlagStatusByCode(ctx context.Context, arg UpdateFlagStatusByCodeParams) error {
	_, err := q.db.ExecContext(ctx, updateFlagStatusByCode,
		arg.Status,
		arg.Msg,
		arg.ResponseTime,
		arg.FlagCode,
	)
	return err
}
