name: Sonar Qube Scan + tests

on:
  push:
    branches:
      # - main
      # - dev
  pull_request:
    branches:
      # - dev
      # - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fix shallow clone warning

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache-dependency-path: cookiefarm/server/go.sum

      - name: Run tests & generate coverage
        working-directory: cookiefarm
        run: |
          mkdir -p ./coverage
          go test work -coverprofile=./coverage/coverage.out -json -v ./... > ./coverage/test_output.json 2>&1 || true

      - name: Fix coverage paths
        run: |
          sed -i 's|^server/|cookiefarm/server/|g' \
            cookiefarm/coverage/coverage.out
          sed -i 's|^server/|cookiefarm/server/|g' \
            cookiefarm/coverage/coverage.out

      - name: SonarQube Scan CookieFarm
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
